let XAxisData = [
  { name: "Jan", sale: 10_000 },
  { name: "Feb", sale: 20_000 },
  { name: "Mar", sale: 50_000 },
  { name: "Apr", sale: 30_000 },
  { name: "May", sale: 40_000 },
  { name: "Jun", sale: 60_000 },
  { name: "Jul", sale: 52_000 },
  { name: "Agu", sale: 10_000 },
  { name: "Sep", sale: 90_000 },
  { name: "Oct", sale: 40_000 },
  { name: "Nov", sale: 10_000 },
  { name: "Dec", sale: 60_000 },
];
let years = [
  { name: "2020", sale: 300_000 },
  { name: "2021", sale: 602_000 },
  { name: "2022", sale: 500_000 },
  { name: "2023", sale: 700_000 },
  { name: "2024", sale: 1_000_000 },
];

const newMembers = [
  {
    id: 1545554,
    name: "John",
    title: "Software Engineer",
    img: "https://avatar.iran.liara.run/public",
  },
  {
    id: 55552,
    name: "Mickle",
    title: "Senior Developer",
    img: "https://via.assets.so/album.png?id=1&q=95&w=360&h=360&fit=fill",
  },
  {
    id: 35255,
    name: "Noah",
    title: "Devops Developer",
    img: "https://loremflickr.com/320/240/boy/all",
  },
  {
    id: 46552343,
    name: "Alice",
    title: "IT",
    img: "https://loremflickr.com/320/240/girl/all",
  },
  {
    id: 52455,
    name: "Mat",
    title: "Developer  Engineer",
    img: "https://avatar.iran.liara.run/public",
  },
  {
    id: 524575,
    name: "Lien",
    title: "Developer  Engineer",
    img: "https://loremflickr.com/320/240/boy/all",
  },
];

const Transactions = [
  {
    id: 1056343,
    customer: "Smith",
    date: "12/ 12 / 2020",
    amount: 123,
    status: "Declined",
    img: "https://avatar.iran.liara.run/public/boy?username=[value]",
    email: "smith@example.com",
  },
  {
    id: 2524,
    customer: "Sydney",
    date: "12/ 12 / 2020",
    amount: 123,
    status: "Approved",
    img: "https://avatar.iran.liara.run/public/girl?username=[value]",
    email: "Sydney@mail.com",
  },
  {
    id: 356343,
    customer: "Saran",
    date: "12/ 12 / 2000",
    amount: 123,
    status: "Pending",
    img: "https://avatar.iran.liara.run/public/girl",
    email: "saran21@gmail.com",
  },
  {
    id: 46543,
    customer: "SJa",
    date: "12/ 12 / 2022",
    amount: 123,
    status: "Declined",
    img: "https://picsum.photos/200/300",
    email: "sja123@aol.com",
  },
  {
    id: 252445,
    customer: "Monica",
    date: "12/ 12 / 2020",
    amount: 123,
    status: "Approved",
    img: "images/profile.jfif",
    email: "monica45@icloud.com",
  },
  {
    id: 576543,
    customer: "Michael",
    date: "12/ 12 / 2020",
    amount: 123,
    status: "Pending",
    img: "https://avatar.iran.liara.run/public/",
    email: "michael85@spa.com",
  },
];

let userRows = [
  {
    id: 1,
    name: "John",
    avatar: "https://avatar.iran.liara.run/public/boy",
    status: "active",
    email: "john@aol.com",
    transaction: "2/8",
  },
  {
    id: 2,
    name: "Sina",
    avatar: "https://avatar.iran.liara.run/",
    status: "non-active",
    email: "john@mail.com",

    transaction: "72",
  },
  {
    id: 3,
    name: "Jo",
    avatar: "https://avatar.iran.liara.run/public/boy",
    status: "active",
    transaction: "22",
    email: "john@outlook.com",
  },
  {
    id: 4,
    name: "Rabin",
    avatar: "https://avatar.iran.liara.run/public/boy",
    status: "active",
    transaction: "2/52",
  },
  {
    id: 5,
    name: "Been",
    avatar: "https://avatar.iran.liara.run/public/girl",
    status: "active",
    transaction: "52",
  },
  {
    id: 6,
    name: "Galas",
    avatar: "https://avatar.iran.liara.run/public/girl",
    status: "active",
    transaction: "0/52",
    email: "john@hotmail.com",
  },
  {
    id: 7,
    name: "Avails",
    avatar: "https://avatar.iran.liara.run/public/girl",
    status: "inactive",
    transaction: "2",
  },
  {
    id: 8,
    name: "Mini",
    avatar: "https://avatar.iran.liara.run/public/girl",
    status: "active",
    transaction: "2",
    email: "jow@hotmail.com",
  },
  {
    id: 9,
    name: "Max",
    avatar: "https://avatar.iran.liara.run/public/girl",
    status: "active",
    transaction: "2/52",
  },
  {
    id: 10,
    name: "John",
    avatar: "https://avatar.iran.liara.run/public/girl",
    status: "inactive",
    transaction: "2/52",
  },
  {
    id: 11,
    name: "Rita",
    avatar: "https://avatar.iran.liara.run/public/",
    status: "active",
    transaction: "2/52",
    email: "john@gmail.com",
  },
  {
    id: 12,
    name: "Tito",
    avatar: "https://avatar.iran.liara.run/public/",
    status: "inactive",
    transaction: "2/52",
    email: "-",
  },
  {
    id: 13,
    name: "Hail",
    avatar: "https://avatar.iran.liara.run/public/",
    status: "active",
    transaction: "2/52",
  },
  {
    id: 14,
    name: "Jorge",
    avatar: "https://avatar.iran.liara.run/public/girl",
    status: "active",
    transaction: "2/52",
  },
  {
    id: 15,
    name: "Germy",
    avatar: "https://avatar.iran.liara.run/public/girl",
    status: "inactive",
    transaction: "2/52",
    email: "john@Aolio.com",
  },
  {
    id: 16,
    name: "Jack",
    avatar: "https://avatar.iran.liara.run/public/girl",
    status: "active",
    transaction: "2/52",
  },
  {
    id: 17,
    name: "Noah",
    avatar: "https://avatar.iran.liara.run/public/girl",
    status: "active",
    transaction: "2/52",
  },
  {
    id: 18,
    name: "Israel",
    avatar: "https://avatar.iran.liara.run/public/girl",
    status: "active",
    transaction: "2/52",
  },
  {
    id: 19,
    name: "Issac",
    avatar: "https://avatar.iran.liara.run/public/girl",
    status: "inactive",
    transaction: "2/52",
  },
  {
    id: 20,
    name: "Mary",
    avatar: "https://avatar.iran.liara.run/public/girl",
    status: "active",
    transaction: "2/52",
  },
  {
    id: 21,
    name: "Nile",
    avatar: "https://avatar.iran.liara.run/public/girl",
    status: "active",
    transaction: "2/52",
  },
  {
    id: 22,
    name: "Anonymous",
    avatar: "https://avatar.iran.liara.run/public/girl",
    status: "active",
    transaction: "2/52",
  },
  {
    id: 23,
    name: "Kobe",
    avatar: "https://avatar.iran.liara.run/public/girl",
    status: "active",
    transaction: "2/52",
  },
  {
    id: 24,
    name: "Rose",
    avatar: "https://avatar.iran.liara.run/public/girl",
    status: "inactive",
    transaction: "2/52",
  },
  {
    id: 25,
    name: "Alice",
    avatar: "https://avatar.iran.liara.run/public/girl",
    status: "active",
    email: "Alice@go.com",
    transaction: "2/52",
  },
  {
    id: 26,
    name: "sara",
    avatar: "https://avatar.iran.liara.run/public/girl",
    email: "sara@gmail.com",
    status: "active",
    transaction: "2/52",
  },
];

let products = [
  {
    id: 1,
    title: "Asus",
    avatars: "images/asus.jpeg",
    price: 890,
  },
  {
    id: 2,
    title: "Acer",
    avatars: "images/acer.jpg",
    price: 890,
  },
  {
    id: 3,
    title: "HP",
    avatars: "images/hp.jpg",
    price: 890,
  },
  {
    id: 4,
    title: "Dell",
    avatars: "/images/dell.jpg",
    price: 890,
  },
];

const productsData = [
  {
    name: "Jan",
    sales: 4000,
  },
  {
    name: "Feb",
    sales: 3000,
  },
  {
    name: "Mar",
    sales: 5000,
  },
];

export {
  XAxisData,
  years,
  newMembers,
  Transactions,
  userRows,
  products,
  productsData,
};
